### ISSUE TITLE
Compatibility with eslint-plugin-import

### ISSUE THREAD

**Issue by oskarer** [asapach/babel-plugin-rewire-exports#12]
When doing an import like;
```
import { rewire$formatNumber, restore } from './utils.js';
```

`eslint-plugin-import` is complaining about `rewire$formatNumber` and `restore` does not exist in `./utils.js`. Is there a way to make this lib make eslint aware of that those functions are available?

**Comment by asapach** [comment]
Just to confirm, is it [`import/named`](https://github.com/benmosher/eslint-plugin-import/blob/HEAD/docs/rules/named.md) rule that is failing?

**Comment by oskarer** [comment]
@asapach Correct, sorry for not clarifying that!

**Comment by asapach** [comment]
Does it still complain if you do it like this?
```js
import * as utils from './utils.js';

utils.rewire$formatNumber();
...
utils.restore();
```

**Comment by oskarer** [comment]
Nope, that works! It's not covered by the `import/named` rule.

**Comment by asapach** [comment]
So will you be fine with using it like that? I think it's a preferred approach for large projects anyway, because you're likely to have multiple modules rewired, and it's easier to distinguish between them:
```js
utils.restore();
services.restore();
```
You could also try using `injector` from #8.

**Comment by oskarer** [comment]
My solution now was doing;

```
/* eslint-disable import/named */
import {
  rewire$someFunction,
  rewire$anotherFunction,
  restore as restoreSelectors,
} from './utils/selectors';
import {
  rewire$helperFunction,
  restore as restoreHelpers,
} from './utils/helpers';
/* eslint-enable import/named */
```

The downside of doing `import * as` is that you don't get tree shaking. However this is not a super big issue in tests so doing your proposed solution will work just fine 👍

**Comment by asapach** [comment]
Thanks. I'll close the issue then.
