### ISSUE TITLE
Has anybody been able to get this lib to play nicely inside a TS based repo?

### ISSUE THREAD

**Issue by glomotion** [asapach/babel-plugin-rewire-exports#31]
so we have a demo repo here: https://github.com/glomotion/stripped-down-next-rewire-ts/tree/tryout/rewire-exports

We're just wondering if anyone has managed to get this lib working well inside a TS repo? It'd be SUPER nice to be able to use TS alongside this lib. 

<img width="681" alt="Screen Shot 2021-07-25 at 11 21 15 am" src="https://user-images.githubusercontent.com/1452237/126884718-6bc97bcd-78dc-4f70-b1b0-a0b72e00f58f.png">

**Comment by asapach** [comment]
I don't think there is a good way to let TS know about the missing types, because they depend on the exports, so I'm afraid the only option I see is to ignore the types entirely. Something like this should work:
```ts
import * as MooComponent from './Moo.component';

(MooComponent as any).rewire$Moo();
```

**Comment by glomotion** [comment]
Yeah I figured as much. Writing tests using jsx instead of ts isn’t the end of the world anyway, IMO. Thanks for the quick reply! :)
