### ISSUE TITLE
Wish: swc/rust based module rewire plugin

### ISSUE THREAD

**Issue by glomotion** [asapach/babel-plugin-rewire-exports#36]
Firstly, just want to say that we LOVE and use this plugin very heavily! Thank you for maintaining it.
Just wondering if there might be any desire to create a similar style plugin for the much speedier rust-based compilers (eg swc)? We'll probably be stuck with babel until this happens, which definitely isn't the end of the world.

**Comment by sergei-startsev** [comment]
@glomotion thanks for your feedback. We're trying to practice dogfooding and swc/rust isn't a part of the primary tech stack we use today, so there're no plans to create a swc plugin for now.
