### ISSUE TITLE
artificially lowers instanbul coverage

### ISSUE THREAD

**Issue by vegetabill** [asapach/babel-plugin-rewire-exports#4]
Hey there this plugin is great but I'm blocked using it on my project because it leads instanbul to report low coverage because obviously the newly generated rewire functions aren't used in most cases.

Is there a way to add an exclude comment to the generated code, something like 

`/* istanbul ignore next */`

So that way the coverage won't be affected?

**Comment by asapach** [comment]
I think if you just need to apply the transform in the right order. I assume you're using https://github.com/istanbuljs/babel-plugin-istanbul?
Then you should do: 
```js
plugins: ["istanbul", "rewire-exports"]
```

**Comment by asapach** [comment]
Although I did try it both ways and get the same results. @vegetabill, could you please share your setup?

**Comment by vegetabill** [comment]
No I'm not using instanbul with babel directly although it sounds like maybe that's better.

I'm using https://github.com/zordius/gulp-jsx-coverage which I see is now marked deprecated and they say to use instanbul directly. I'll try to migrate which should fix the issue. If it doesn't, I'll re-open with a test case.

Thanks!

**Comment by asapach** [comment]
Thanks 👍
