### ISSUE TITLE
support typescript

### ISSUE THREAD

**Issue by dotennin** [asapach/babel-plugin-rewire-exports#40]
> '"@/store/modules/pages/home"' has no exported member named 'rewire$XXX'. Did you mean 'XXX'? (tsserver 2724)

Got this error when importing `rewireXXX` in the test file .
Any good idea for Typescript support ?*excepts ts-ignore.

**Comment by sergei-startsev** [comment]
```ts
import * as bar from './bar';

(<any>bar).fooXXX();
```

**Comment by asapach** [comment]
I don't think a babel plugin can really do much to address this. I would suggest either following @sergei-startsev's example or adding a dummy function declaration to the source module to satisfy type checking, e.g.:
```ts
export declare function rewire$XXX(_: any): void;
export declare function restore(): void;
```

**Comment by dotennin** [comment]
> I don't think a babel plugin can really do much to address this. I would suggest either following @sergei-startsev's example or adding a dummy function declaration to the source module to satisfy type checking, e.g.:
> 
> ```ts
> export declare function rewire$XXX(_: any): void;
> export declare function restore(): void;
> ```

Yeah , In addition to trouble, but this is the safest. we need to add a corresponding declaration for each variable that needs to be mocked,

> ```ts
> import * as bar from './bar';
> 
> (<any>bar).fooXXX();
> ```
It's also a good idea,


Actually I did the following way to resolve this issue. 
``` typescript
const foo = require('path to file')
foo.rewire$XXX(() => mockXXX);
```
This is my current simpler way of avoiding `any` and `ts-ignore` etc.(but loses type checking 😢 )
Thanks for your advice.
