### ISSUE TITLE
Dedupe `restore` export

### ISSUE THREAD

**Issue by rhysviz** [asapach/babel-plugin-rewire-exports#44]
I'm trying to use this in a project where I am upgrading to webpack 5. I am compiling my tests with webpack and it produces the following error:

```
Uncaught Error: Module parse failed: Duplicate export 'restore'
```

Is it possible to make the restore export related to the import name somehow to avoid this issue? i.e.

```
import { restoreModuleA } from 'module-a';
import { restoreSomePathFile } from '../some/path/file';
```

**Comment by asapach** [comment]
Could you please provide a more complete example with repro steps?

**Comment by rhysviz** [comment]
In trying to reproduce this I realised it was just an error resulting from quite a complicated webpack set up 😬 

I was basically running babel (with rewire) twice on some files which explains the error.

Thanks for the library 😃
