### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by jDeppen** [asapach/babel-plugin-rewire-exports#7]
Would you consider adding a changelog, please? Thanks
http://keepachangelog.com/en/1.0.0/

**Comment by asapach** [comment]
@jDeppen, is there an automated tool or bot that you can recommend?

**Comment by jDeppen** [comment]
Hmm, I don't know of anything like that. Maybe just note anything on [releases](https://github.com/asapach/babel-plugin-rewire-exports/releases) users might feel is important so they can easily upgrade? Thanks for your work here and anything you can add for a changelog!

**Comment by asapach** [comment]
All the significant changes are now noted in the [release notes](https://github.com/asapach/babel-plugin-rewire-exports/releases).
